#!/bin/bash

##
# Print a notification, if current directory was renamed or does not
# exist
#
# Params:
# - $1 Prefix
# - $2 Suffix
PS1_cwd_check ()
{
    REAL_CWD="$( { cd . || return ; pwd; } 2>/dev/null ; )"
    if [ "${REAL_CWD}" != "${PWD}" ]
    then
        if [[ "${REAL_CWD}" =~ /\.$ ]]
        then
            # shellcheck disable=SC2059
            printf " $1CWD has been deleted$2"
        else
            printf " $1CWD=%s$2" "${REAL_CWD}"
        fi
    fi
}
