#!/bin/bash

##
# Print number of directories in dir stack (pushd)
#
# Params:
# - $1: Will be prepended to printed value, if any.
PS1_dirstack_size () {
    SIZE=${#DIRSTACK[@]}
    SIZE=$(( SIZE - 1 ))
    if [ $SIZE -gt 0 ]
    then
        # shellcheck disable=SC2059
        printf "$1+$SIZE"
    fi
}

