#!/bin/sh

##
# Print whether dropbox is idle
#
# Params:
# - $1: Will be printed if dropbox is not idle
# - $2: Will be printed if dropbox is idle
PS1_dropbox () {
    if ( which dropbox &>/dev/null )
    then
        status="$( command dropbox filestatus . )"
        if [ ".: syncing" = "$status" ]
        then
            echo -n "$1"
        elif [ ".: up to date" = "$status" ]
        then
            echo -n "$2"
        fi
    fi
}

