#!/bin/bash

##
# Print number of stashed changes, if any
#
# Params:
# - $1: Will be prepended to returned value, if any.
# - $2: Will be appended, if any output
PS1_git_stash () {
    STASH_COUNT="$(( $( PS1_git_stash__get ) ))"
    test "$STASH_COUNT" = "0" || printf "$1$STASH_COUNT$2"
}

##
# Get number of stashed changes.
PS1_git_stash__get () {
    command git stash list 2>/dev/null | wc -l
}

