#!/bin/bash

##
# Print git status
#
# Params:
# - $1: Will be prepended to staging status, if any
# - $2: Will be prepended to working copy status, if any
# - $3: Will be appended, if any output
PS1_git_status () {
    STATUS="$( command git status --porcelain 2>/dev/null | cut -b1-2 )"
    STAGING_STATUS="$(     echo "${STATUS}" | cut -b1 | grep -v '^[[:space:]?]*$' | sort | uniq -c | xargs printf "%s%s" )"
    WORKINGCOPY_STATUS="$( echo "${STATUS}" | cut -b2 | grep -v '^[[:space:]]*$'  | sort | uniq -c | xargs printf "%s%s" )"
    if [ -n "${PS1_UTF_SUPPORT}" ] || [ "UTF-8" = "$( locale charmap )" ]
    then
        STAGING_STATUS="$( echo "$STAGING_STATUS"         | sed -e s/0/⁰/g -e s/1/¹/g -e s/2/²/g -e s/3/³/g -e s/4/⁴/g -e s/5/⁵/g -e s/6/⁶/g -e s/7/⁷/g -e s/8/⁸/g -e s/9/⁹/g -e s/A/ᵃ/g -e s/M/ᵐ/g -e s/D/ᵈ/g -e s/R/ʳ/g )"
        WORKINGCOPY_STATUS="$( echo "$WORKINGCOPY_STATUS" | sed -e s/0/₀/g -e s/1/₁/g -e s/2/₂/g -e s/3/₃/g -e s/4/₄/g -e s/5/₅/g -e s/6/₆/g -e s/7/₇/g -e s/8/₈/g -e s/9/₉/g -e s/A/ₐ/g -e s/M/ₘ/g -e s/D/d/g -e s/R/ᵣ/g -e s/U/ᵤ/g -e s/?/?/g )"
    fi
    test -n "$STAGING_STATUS"     && printf "$1$STAGING_STATUS"
    test -n "$WORKINGCOPY_STATUS" && printf "$2$WORKINGCOPY_STATUS"
    test -n "$STAGING_STATUS" || test -n "$WORKINGCOPY_STATUS" && printf "$3"
}
