#!/bin/sh

. ./git_rebase
. ./git_merge

##
# Print active git branch name.
#
# Params:
# - $1: Will be prepended to printed value, if any.
PS1_git_branch () {
    LABEL="$( PS1_git_branch__get_label )"

    if [ -n "$LABEL" ]
    then
        if ( command git config --get alias.grows-from > /dev/null )
        then
            BRANCH="$( PS1_git_branch__get )"
            GROWS_FROM="$( command git grows-from "$BRANCH" )"
            if [ -n "$GROWS_FROM" ] && [ "$BRANCH" != "$GROWS_FROM" ]
            then
                LABEL="$LABEL ~ $GROWS_FROM"
            fi
        fi
    fi

    if [ -n "$LABEL" ]
    then
        printf "$1($LABEL)"
    fi
}

##
# Get active git branch name.
PS1_git_branch__get () {
    command git rev-parse --abbrev-ref HEAD 2>/dev/null
}

##
# Get active git branch human readable name.
PS1_git_branch__get_label () {
    command git branch 2>/dev/null | GREP_OPTIONS= grep '^\*' | cut -b3-
}
