#!/bin/sh

. ./git_rebase
. ./git_merge

##
# Print active git branch name.
#
# Params:
# - $1: Will be prepended to printed value, if any.
PS1_git_branch () {
    BRANCH="$( PS1_git_branch__get )"
    LABEL="$BRANCH"

    if [ -n "$LABEL" ]
    then
        if ( PS1_git_rebase__get )
        then
            if [ "HEAD" = "$LABEL" ]
            then
                LABEL="(rebasing)"
            else
                LABEL="$LABEL (rebasing)"
            fi
        fi
    fi

    if [ -n "$LABEL" ]
    then
        if ( PS1_git_merge__get )
        then
            if [ "HEAD" = "$LABEL" ]
            then
                LABEL="(merging)"
            else
                LABEL="$LABEL (merging)"
            fi
        fi
    fi

    if [ -n "$LABEL" ]
    then
        if ( command git config --get alias.grows-from > /dev/null )
        then
            GROWS_FROM="$( command git grows-from )"
            if [ -n "$GROWS_FROM" ] && [ "$BRANCH" != "$GROWS_FROM" ]
            then
                LABEL="$LABEL ~ $GROWS_FROM"
            fi
        fi
    fi

    if [ -n "$LABEL" ]
    then
        printf "$1($LABEL)"
    fi
}

##
# Get active git branch name.
PS1_git_branch__get () {
    command git rev-parse --abbrev-ref HEAD 2>/dev/null
}
