#!/bin/bash

##
# Print number of background jobs.
#
# Params:
# - $1: Will be prepended to returned value, if any.
PS1_jobcount () {
    COUNT=$( jobs | wc -l )
    if [ "$COUNT" == 1 ]
    then
        printf "$1(%s job)" "$COUNT"
    elif [ "$COUNT" != 0 ]
    then
        printf "$1(%s jobs)" "$COUNT"
    fi
}
