#!/bin/bash

##
# Print last executed command's status code
#
# Params:
# - $1: Will be prepended to last command's return code
#       (displayed only if non-zero).
PS1_lastcmd_status () {
    STATUS="$( PS1_lastcmd_status__get )"
    if [ -n "$STATUS" ]
    then
        if [ "UTF-8" = "$( locale charmap )" ]
        then
            printf "$1%s" "↖ $STATUS"
        else
            printf "$1returned %s" "$STATUS"
        fi
    fi
}

##
# Get last executed command's status code
#
# Uses:
# - $PS1_lastcmd_status__status
PS1_lastcmd_status__get () {
    if [ -z "$PS1_lastcmd_status__status" ]
    then
        printf "\nDid you register debug trap in your PS1 preset?\ntrap \$PS1_debug_trap DEBUG\n."
    elif [ 0 -ne "$PS1_lastcmd_status__status" ]
    then
        printf "%s" "$PS1_lastcmd_status__status"
    fi
}

##
# Save last executed command's status code
PS1_lastcmd_status__save () {
    export PS1_lastcmd_status__status="$?"
}

if ! ( echo "$PROMPT_COMMAND" | grep -q PS1_lastcmd_status__save )
then
    export PROMPT_COMMAND="PS1_lastcmd_status__save;$PROMPT_COMMAND"
fi
