#!/bin/bash

##
# Print last executed command's execution time
#
# Params:
# - $1: Will be prepended to last command's execution time
#       (displayed only if non-zero).
PS1_lastcmd_time () {
    TIME="$( PS1_lastcmd_time__get )"
    if [ -n "$TIME" ]
    then
        if [ "UTF-8" = "$( locale charmap )" ]
        then
            printf "$1⭦ %s" "$TIME"
        else
            printf "$1took %s" "$TIME"
        fi
    fi
}

##
# Get last executed command's execution time
#
# Uses:
# - $PS1_lastcmd_time__seconds Execution time.
PS1_lastcmd_time__get () {
    CMD_SEC="$PS1_lastcmd_time__seconds"
    if [ -z "$CMD_SEC" ]
    then
        printf "\nDid you register debug trap in your PS1 preset?\ntrap \$PS1_debug_trap DEBUG\n."
    elif [ 0 -ne "$CMD_SEC" ] && [ 0 -lt "$CMD_SEC" ]
    then
        if [ "$CMD_SEC" -gt 60 ]
        then
            # 50% volume
            PLAY="paplay --volume=32768"
            SOUND=/usr/share/sounds/gnome/default/alerts/glass.ogg
            # shellcheck disable=SC2086
            if ( command -v $PLAY >/dev/null) && [ -e $SOUND ]
            then
                # shellcheck disable=SC2086
                $PLAY "$SOUND" >/dev/null 2>&1 &
            fi
        fi
        CMD_MIN=$(( CMD_SEC / 60 ))
        CMD_SEC=$(( CMD_SEC - CMD_MIN * 60 ))
        CMD_HRS=$(( CMD_MIN / 60 ))
        CMD_MIN=$(( CMD_MIN - CMD_HRS * 60 ))
        if [ 0 -ne $CMD_HRS ]
        then
            printf "%d:%02d:%02d" "$CMD_HRS" "$CMD_MIN" "$CMD_SEC"
        elif [ 0 -ne $CMD_MIN ]
        then
            printf "%d:%02d" "$CMD_MIN" "$CMD_SEC"
        else
            printf "%ds" "$CMD_SEC"
        fi
    fi
}

##
# Stop counting execution time
#
# Uses:
# - $PS1_lastcmd_time__seconds Execution time.
# - $PS1_lastcmd_time__seconds_start Start of execution.
PS1_lastcmd_time__stop () {
    if [ -n "${PS1_lastcmd_time__seconds_start}" ]
    then
        PS1_lastcmd_time__seconds=$(( SECONDS - PS1_lastcmd_time__seconds_start ))
    else
        PS1_lastcmd_time__seconds=0
    fi
    unset PS1_lastcmd_time__seconds_start
}

##
# Start counting execution time
#
# Uses:
# - $PS1_lastcmd_time__seconds_start Start of execution.
PS1_lastcmd_time__start () {
    if [ -z "${PS1_lastcmd_time__seconds_start}" ]
    then
        export PS1_lastcmd_time__seconds_start=${SECONDS}
    fi
}

# This variable should be registered as DEBUG grap in the preset file.
export PS1_debug_trap="PS1_lastcmd_time__start;$PS1_debug_trap"
if ! ( echo "$PROMPT_COMMAND" | grep -q PS1_lastcmd_time__stop )
then
    export PROMPT_COMMAND="PS1_lastcmd_time__stop;$PROMPT_COMMAND"
fi
