#!/bin/sh

##
# Print info if current shell if a vim subshell.
#
# Params:
# - $1: Will be displayed if yes
# - $2: Will be displayed if no
PS1_subshell_vim () {
    if [ -n "$VIMRUNTIME" ]
    then
        printf "$1"
    else
        printf "$2"
    fi
}
