#!/bin/sh

##
# Print info if current shell if a vim subshell.
#
# Params:
# - $1: Will be prepended to returned value, if any.
PS1_subshell_vim () {
    if [ -n "$VIMRUNTIME" ]; then
        printf "$1(vim shell)"
    fi
}
