#!/bin/bash
# shellcheck disable=SC1091

# Load modules
. ./title

##
# Set terminals and screen(1) window titles.
#
# Uses:
# - $TERM terminal type
# - $WINDOW screen(1) window number
# - $STY screen(1) identifier
PS1_titles () {
    TITLE="$( PS1_title )"

    # change the window title of X terminals
    case ${TERM} in
        xterm*|rxvt*|Eterm|aterm|kterm|gnome)
            echo -ne "\033]0;${TITLE}\007"
            ;;

        screen*|tmux*)
            echo -ne "\ek${TITLE}\e\\"

            SCREEN_NAME="$( echo "$STY" | cut -d. -f2- )"
            [ -n "${WINDOW}" ] && SCREEN_NAME="${SCREEN_NAME}(${WINDOW})"
            if [ -n "${SCREEN_NAME}" ]
            then
                SCREEN_TITLE="${SCREEN_NAME} - ${SCREEN_TITLE}"
            else
                SCREEN_TITLE="${TITLE}"
            fi
            echo -ne "\033_${TITLE}\033\\"
            ;;
    esac
}

export PS1_debug_trap="PS1_titles;$PS1_debug_trap"
