#!/bin/bash

# Load modules
. ./breadcrumbs

##
# Print text suitable for terminal/screen(1) window title
#
# Uses:
# - $BASH_COMMAND
# - $SSH_CONNECTION
# - $SUDO_USER
# - $USER
# - $HOSTNAME
PS1_title ()
{
    if ! [[ "$BASH_COMMAND" =~ ^PS1_ ]] && [ "$BASH_COMMAND" != 'echo "$BASH_COMMAND"' ] && [ "$BASH_COMMAND" != 'kill -STOP $$' ]
    then
        echo "$BASH_COMMAND"

        if [ -n "$SUDO_USER" ]
        then
            echo " as $USER"
        fi
        if [ -n "$SSH_CONNECTION" ]
        then
            printf "@$HOSTNAME"
        fi
    else
        if [ -n "$SUDO_USER" ]
        then
            printf "$USER"
        fi
        if [ -n "$SSH_CONNECTION" ]
        then
            printf "@$HOSTNAME"
        fi

        printf :
        PS1_breadcrumbs
    fi
}
