#!/bin/bash
# shellcheck disable=SC1091

# Load modules
. ./breadcrumbs

##
# Print text suitable for terminal/screen(1) window title
#
# Uses:
# - $BASH_COMMAND
# - $SSH_CONNECTION
# - $SUDO_USER
# - $USER
# - $HOSTNAME
PS1_title ()
{
    # shellcheck disable=SC2016
    if ! [[ "$BASH_COMMAND" =~ ^PS1_ ]] && [ "$BASH_COMMAND" != 'echo "$BASH_COMMAND"' ] && [ "$BASH_COMMAND" != 'kill -STOP $$' ]
    then
        echo "$BASH_COMMAND"

        if [ -n "$SUDO_USER" ]
        then
            printf " as %s" "$USER"
        fi
        if [ -n "$SSH_CONNECTION" ]
        then
            printf "@%s" "$HOSTNAME"
        fi
    else
        if [ -n "$SUDO_USER" ]
        then
            printf "%s" "$USER"
        fi
        if [ -n "$SSH_CONNECTION" ]
        then
            printf "@%s" "$HOSTNAME"
        fi

        printf :
        PS1_breadcrumbs
    fi
}
