#!/bin/bash
# User-specific colour (31-36)
#
# Script params:
#
# - $1: colour for root user
# - $2: colour for other users
#       Leave empty to generate colour from host name.

ROOT_COLOUR_NO=${1:-31}

if [ "$EUID" == "0" ]
then
    PS1_user_colour="1;${ROOT_COLOUR_NO}"
elif [ -n "$2" ]
then
    PS1_user_colour="$2"
else
    MD5CMD="$( which md5sum || which md5 )"
    if [ -n "${MD5CMD}" ]
    then
        USERNAME_HASH=$( whoami | "${MD5CMD}" )
        if [ "$( tput colors )" -ge 256 ]
        then
            PS1_user_colour="$( tput setaf $(( 0x${USERNAME_HASH:2:2} )) )"
        else
            # values from 31-35 (all colours, but black and white and last
            # one)
            PS1_user_colour=$(( 0x${USERNAME_HASH:2:1} * 6 / 16 + 31 ))
            # do not include root's colour
            if (( PS1_user_colour >= ROOT_COLOUR_NO ))
            then
                PS1_user_colour=$(( PS1_user_colour + 1 ))
            fi
            PS1_user_colour="\e[${PS1_user_colour}m"
        fi
    fi
fi

export PS1_user_colour
