#!/bin/bash
# User name and host printed in their specific colours
# shellcheck disable=SC1091,SC2154

# Load modules
. ./user_colour
. ./host_colour

# For host use black text and host–specific colour as background
export PS1_user_and_host="${PS1_user_colour}\u\e[0;30m${PS1_host_colour}@\h"
