#!/bin/bash
# User-specific colour
#
# Script params:
#
# - $1: colour for root user
# - $2: colour for other users
#       Leave empty to generate colour from host name.

if [ -z "${ROOT_COLOUR}" ]
then
    if [ "$( tput colors )" -ge 256 ]
    then
        ROOT_COLOUR="\e[1;31m"
    else
        ROOT_COLOUR="$( tput bold; tput setaf 196 )"
    fi
fi

if [ "$EUID" == "0" ]
then
    PS1_user_colour="${ROOT_COLOUR}"
elif [ -n "$2" ]
then
    PS1_user_colour="$2"
elif [ -x ~/.config/usercolour ]
then
    PS1_user_colour="$( ~/.config/usercolour )"
fi

if [ -z "${PS1_user_colour}" ]
then
    MD5CMD="$( which md5sum || which md5 )"
    if [ -n "${MD5CMD}" ]
    then
        USERNAME_HASH=$( whoami | "${MD5CMD}" )
        CODE=$(( 0x${USERNAME_HASH:27:1}${USERNAME_HASH:3:1} - 12 ))
        CODE=$(( (CODE-2) % 220 + 2 ))

        # blacks (unreadable on most terminals)
        if (( CODE == 0 )) || (( CODE == 16 ))
        then
            CODE=$(( ( CODE + 128 ) % 222 ))
        fi
        # reds (reserved for root)
        if (( CODE == 9 )) || (( ( CODE-52 )%36 == 0 && CODE >= 52 ))
        then
            CODE=$(( ( CODE + 128 ) % 222 ))
        fi

        if [ "$( tput colors )" -ge 256 ]
        then
            PS1_user_colour="$( tput setaf $CODE )"

            # do not include root's colour
            if [ "${PS1_user_colour}" = "${ROOT_COLOUR}" ]
            then
                CODE=$(( ( CODE + 128 ) % 222 ))
                PS1_user_colour="$( tput setaf $CODE )"
            fi
        else
            CODE=$(( CODE % 6 + 32 ))
            PS1_user_colour="\e[${CODE}m"

            # do not include root's colour
            if [ "${PS1_user_colour}" = "${ROOT_COLOUR}" ]
            then
                CODE=$(( CODE + 1 ))
                PS1_user_colour="\e[${CODE}m"
            fi
        fi
        unset CODE
        unset USERNAME_HASH
    fi
    unset MD5CMD
fi

export PS1_user_colour
