#!/bin/bash
# (c) Marek `saji' Augustynowicz

##
# {GIT_TAG}{GIT_STASH_COUNT} {SYSTEM DEFAULT PROMPT}
#
# It may look like this:
#
# (zar-1.0)+3 ~/src/foo $
##

# Have to change directory to `modules/`, as modules depend on
# that when loading other modules.
cd "$( dirname "${BASH_ARGV[0]}" )/../modules"
. ./git_tag
. ./git_stash
. ./git_counters
. ./git_status
cd - >/dev/null

if [ "UTF-8" = "$( locale charmap )" ]
then
    PS1_ICON_GIT_STASHED=+
    PS1_ICON_GIT_BEHIND=⊝
    PS1_ICON_GIT_AHEAD=⊕
else
    PS1_ICON_GIT_STASHED=+
    PS1_ICON_GIT_BEHIND=-
    PS1_ICON_GIT_AHEAD=+
fi

export PS1='$(
    # current git tag (or branch name, if tag does not exist)
    #             blue
    PS1_git_tag "\e[0;34m"

    # number of git-stashed changes
    #             bold black
    PS1_git_stash "\e[1;30m${PS1_ICON_GIT_STASHED}"

    # git counters:  stashed,    behind,     ahead
    #                bold black, blue,       bold blue
    PS1_git_counters "\e[1;30m${PS1_ICON_GIT_STASHED}" "\e[0;34m${PS1_ICON_GIT_BEHIND}" "\e[1;34m${PS1_ICON_GIT_AHEAD}"

    # git status:  staging,    working copy
    #              bold cyan, cyan
    PS1_git_status "\e[1;36m" "\e[0;36m"
)\e[0m '"$PS1"
